# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "CV"
  url = "files/cv.pdf"
  weight = 10

[[main]]
  name = "Job Market Paper"
  url = "#JMP"
  weight = 20
  
[[main]]
  name = "Working papers"
  url = "#WP"
  weight = 30

[[main]]
    name = "Work In Progress"
    url = "#WIP"
    weight = 40

[[main]]
  name = "Selected Awards"
  url = "#awards"
  weight = 60

[[main]]
    name = "Teaching"
    url = "#teaching"
    weight = 50

[[main]]
  name = "Useful Codes"
  url = "#codes"
  weight = 70
  
[[main]]
  name = "Contact"
  url = "#contact"
  weight = 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
